config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :features, only: [:new, :create, :destroy]
    resources :updates, only: [:new, :create, :destroy]
  end
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :project

  validates :body, presence: true
  validates :project, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :features
  has_many :updates

  validates :title, presence: true
  validates :description, presence: true
  validates :github_link, presence: true
end

app/models/update.rb
class Update < ActiveRecord::Base
  belongs_to :project

  validates :body, presence: true
  validates :project, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @feature =  Feature.new
  end

  def create
    @updates = []
    @project = Project.find(params[:project_id])
    @features = @project.features.order(created_at: :asc)
    @feature = Feature.new(feature_params)
    @feature.project = @project

    if @feature.save
      flash[:notice] = 'Feature successfully added!'
      redirect_to project_path(@project)
    else
      flash[:alert] = "Feature was not saved. #{@feature.errors.full_messages.join ", "}."
      render :'features/new'
    end
  end

  private

  def feature_params
    params.require(:feature).permit(:body).merge(project: Project.find(params[:project_id]))
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order(updated_at: :desc)
  end

  def show
    @project = Project.find(params[:id])
    @features = @project.features.order(updated_at: :desc)
    @feature = Feature.new
    @updates = @project.updates.order(updated_at: :desc)
    @update = Update.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project added!"
      redirect_to projects_path
    else
      flash[:alert] = "Please make sure all fields are filled in!"
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @features = @project.features
    @updates = @project.updates

    if @project.destroy!
      @features.map { |feature| feature.destroy! }
      @updates.map { |update| update.destroy! }

      flash[:notice] = "Project deleted!"
    end
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(
      :title,
      :description,
      :github_link
    )
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @update =  Update.new
  end

  def create
    @features = []
    @project = Project.find(params[:project_id])
    @updates = @project.updates.order(created_at: :asc)
    @update = Update.new(update_params)
    @update.project = @project

    if @update.save
      flash[:notice] = 'Activity successfully added!'
      redirect_to project_path(@project)
    else
      flash[:alert] = "Activity was not saved. #{@update.errors.full_messages.join ", "}."
      render :'updates/new'
    end
  end

  private

  def update_params
    params.require(:update).permit(:body).merge(project: Project.find(params[:project_id]))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/features/new.html.erb
<h2>Add a feature for <%= @project.title %></h2>

<%= form_for [@project, @feature] do |f| %>
  <%= f.label :body, "Description" %>
  <%= f.text_field :body %>
  <%= f.submit "Add feature" %>
<% end %>

<%= link_to 'Go home', projects_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Project Tracker" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <% if flash.any? %>
      <div class="flash">
        <div class="container">
          <%= flash[:notice] %>
          <%= flash[:alert] %>
        </div>
      </div>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="column">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/projects/index.html.erb
<h1>Get to work!</h1>

<div class="callout">
<% @projects.each do |project| %>
<li><%= link_to project.title, project %>, added <%= project.created_at.strftime("%B %d %Y") %></li>
<% end %>
</div>

<%= link_to 'Add a new project', new_project_path %>

app/views/projects/new.html.erb
<h1>Add a new project</h1>

<%= form_for @project do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :github_link, 'GitHub' %>
    <%= f.text_field :github_link %>
  </div>

  <div class="field">
    <%= f.submit "Submit project" %>
  </div>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<ul class="menu">
  <li><a href="<%= @project.github_link %>">GitHub link</a></li>
  <li><%= link_to 'Go home', projects_path %></li>
  <li><a href="https://www.reddit.com/r/kittens/">Distract me!</a></li>
  <li><%= button_to "Delete project", project_path(@project), method: :delete %></li>
</ul>

<div class="text-center">
    <p><%= @project.description %></p>
</div><br />

<div class="small-6 columns">
  <div class="callout">
    <h4>Features</h4>

    <% @features.each do |feature| %>
    <li><%= feature.body %></li>
    <% end %><br />
    <%= link_to 'Add feature', new_project_feature_path(@project) %>
  </div>
</div>

<div class="small-6 columns">
  <div class="callout">
    <h4>Recent Activity</h4>

    <% @updates.each do |update| %>
    <li><%= update.body %> | <%= update.created_at.strftime("%B %d %Y") %></li>
    <% end %><br />
    <%= link_to 'Add activity', new_project_update_path(@project) %>
  </div>
</div>

app/views/updates/new.html.erb
<h2>Add activity for <%= @project.title %></h2>

<%= form_for [@project, @update] do |f| %>
  <div class="field">
    <%= f.label :body, "Activity" %>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.submit "Add activity" %>
  </div>
<% end %>

<%= link_to 'Go home', projects_path %>